[package]
name = 'Deployer'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '985f19d40457a5f09f2d741b1feca6bf7ba1f8a6'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
deployer="0x277fa055b6a73c42c0662d5236c65c864ccbf2d4abd21f174a30c8b786eab84b"
