[package]
name = 'Deployer'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '985f19d40457a5f09f2d741b1feca6bf7ba1f8a6'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
# This is testnet address. source: https://docs.pyth.network/consume-data/aptos
deployer = "0xb31e712b26fd295357355f6845e77c888298636609e93bc9b05f0f604049f434"
