[package]
name = "TokenBridge"
version = "0.0.1"

#TODO: pin versions before mainnet release
[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "movement" }
Wormhole = { local = "../wormhole/" }
Deployer = { local = "../deployer/" }

# only included in testing
[dev-dependencies]
TestCoin = { local = "../coin/" }

[addresses]
token_bridge = "0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f"
