[package]
name = "Wormhole"
version = "0.0.1"
upgrade_policy = "compatible"

#TODO: pin versions before mainnet release
[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "movement" }
Deployer = { local = "../deployer/" }

[addresses]
wormhole = "0x9236893d6444b208b7e0b3e8d4be4ace90b6d17817ab7d1584e46a33ef5c50c9"
